from enum import Enum

from langchain_core.runnables.base import RunnableLike

from ..data import load_questions, prepare_retriever, save
from ..features.dataset_builder import (
    dataset_invoker_chain_builder,
    dataset_invoker,
    validate,
)
from ..llm import (
    load_model,
    prepare_for_inference,
    inference,
    retrieve_input,
    validate_input,
)
from ..utils.runmode_check import check_runmode


class Nodes(Enum):
    """
    Nodes in the state graph.\n
    Their identifiers are defined with prefix for each node type.\n
    - `c` for conditional nodes
    - `hi` for human interface nodes
    - `ds` for dataset nodes
    - `lm` for language model nodes
    - `vt` for vector database nodes
    """

    RETRIEVER_PREPARER = "vt_preparer_retriever"
    """VectorDB retriever preparation node"""
    RUNMODE_CHECKER = "c_check_runmode"
    """Run mode checker conditional node"""

    # RAFT Dataset Builder
    RF_MODEL_LOADER = "lm_loader_model"
    """LLM model loader node"""
    RF_QUESTIONS_LOADER = "ds_loader_questions"
    """Questions dataset loader node"""
    RF_INVOKER_CHAIN_BUILDER = "lm_builder_invoker_chain"
    """
    Langchain invoker builder node

    Create an `Iterator` which inference the language model with the questions using langchain.
    """
    RF_QA_INVOKER = "lm_invoker_qa"
    """
    Question answering language model inference node

    Actually invokes iteration of chains to generate responses for prompts and save them as a dataset.
    """
    RF_ANSWER_VALIDATOR = "c_validator_answer"
    """
    Answer validation node

    Validate the answers generated by the language model using Ragas framework.
    """
    RF_QA_DATASET_CHECKPOINTER = "ds_checkpoint_qa"
    """
    Question answering dataset checkpointing node

    Finally save the dataset generated by the language model.
    """

    # Question Answering
    INFERENCE_PREPARER = "lm_preparer_inference"
    """Inference preparation language model node"""
    INPUT_RETRIEVER = "hi_input_retriever"
    """Input retriever conditional node"""
    INPUT_VALIDATOR = "c_input_validator"
    """Input validation conditional node"""
    RESULT_INFERENCER = "lm_inferencer_result"
    """Result inference language model inference node"""

    @property
    def is_conditional(self) -> bool:
        """
        Check if the node is conditional.\n
        :return: True if the node is conditional, False otherwise
        """
        return self.key.split("_")[0] == "c"

    @property
    def key(self) -> str:
        """
        Get the key of the node.\n
        :return: key of the node
        """
        return self.value

    @property
    def runnable(self) -> RunnableLike:
        """
        Get the runnable for the node.\n
        :return: Runnable for the node
        """
        if self is Nodes.RETRIEVER_PREPARER:
            return prepare_retriever
        elif self is Nodes.RUNMODE_CHECKER:
            return check_runmode

        # RAFT Dataset Builder
        elif self is Nodes.RF_MODEL_LOADER:
            return load_model
        elif self is Nodes.RF_QUESTIONS_LOADER:
            return load_questions
        elif self is Nodes.RF_INVOKER_CHAIN_BUILDER:
            return dataset_invoker_chain_builder
        elif self is Nodes.RF_QA_INVOKER:
            return dataset_invoker
        elif self is Nodes.RF_ANSWER_VALIDATOR:
            return validate
        elif self is Nodes.RF_QA_DATASET_CHECKPOINTER:
            return save

        # Question Answering
        elif self is Nodes.INFERENCE_PREPARER:
            return prepare_for_inference
        elif self is Nodes.INPUT_RETRIEVER:
            return retrieve_input
        elif self is Nodes.INPUT_VALIDATOR:
            return validate_input
        elif self is Nodes.RESULT_INFERENCER:
            return inference
        else:
            raise ValueError(f"Runnable for node {self} is not defined.")

    @property
    def node_action_binding(self) -> tuple[str, RunnableLike]:
        """
        Get the id and runnable for the node.\n
        :return: Tuple of id and runnable for the node
        """
        return self.key, self.runnable
